### ISSUE TITLE
扫码签到的api

### ISSUE THREAD

**Issue by Jingzhe-Studio** [DGYJ-fufu/nonebot-plugin-pu-activity#1]
能否增加批量扫码签到功能

**Comment by DGYJ-fufu** [comment]
你是指签到员给参加人员的扫码签到功能？

**Comment by Jingzhe-Studio** [comment]
是的，因为有线上签到需求，我觉得可以结合qq机器人实现发签到码自动扫码签到功能

**Comment by DGYJ-fufu** [comment]
1.我是参与者的角色来进行开发的，我不太清楚签到员与参与者之间的签到在程序上是如何运作的，我也没有签到员账号来进行测试。
2.如果你是签到员的角色来使用，因为签到码是有时效的，并且我认为收集这些有效的签到码是一个很麻烦的事情，而现在参与者来了之后只需要扫一下码，我觉得这个过程并不麻烦
3.如果你是参与者的角色来使用，如果这个功能做出来的前提下，你需要一个这个活动的签到员账号才可以进行签到操作，那么话又说回来，你都有签到员账号了，给你签个到我相信这不是难事
你可以具体说说你是什么样的角色，需要什么样的需求

**Comment by Jingzhe-Studio** [comment]
不好意思，我的描述比较模糊。具体来说，作为一个线上活动的签到员，因为参与者无法线下扫码签到，需要让参与者把签到码发给自己或者发到一个群里，用手机对着电脑屏幕扫码签到。由于签到码有时效性，这个过程很困难。因此我想开发一个QQ机器人，收到参与者发的签到码后调用pu相关的api进行签到，然后向参与者回复签到结果。我有管理员账号，但是学校近期没有可供测试的活动，没法抓包测试扫码签到的接口，于是想问问有没有已知的api。感谢你的回复，以后有可供测试活动我会自行测试的。

**Comment by DGYJ-fufu** [comment]
我明白你的需求了，如果可以有管理员账号和活动进行测试，确实可以对这个需求进行开发，我没有管理员账号，所以没有对这方面的接口测试
