### ISSUE TITLE
找不到id

### ISSUE THREAD

**Issue by CheXinyu** [DGYJ-fufu/nonebot-plugin-pu-activity#2]
找不到南京工业大学的ID

**Comment by DGYJ-fufu** [comment]
估计是学校在PU口袋里面的全称不对，你可以在[https://pc.pocketuni.net/chooseSchool](url)中去查找一下你们学校的具体全称，或者你有登录PU口袋校园APP的情况下可以在APP的我的页面顶端的用户名称下方会有学校在PU口袋中的具体全称。
本项目是直接使用PU口袋校园的学校id接口来请求的学校id列表，然后根据用户输入的学校名称来进行匹配对应的sid，所以如果PU口袋的学校列表里面没有或者学校在PU口袋的全称不一样，可能就会导致sid获取失败。

**Comment by DGYJ-fufu** [comment]
感谢你的反馈，我发现PU口袋更换了sid请求接口，我会对新的请求接口进行适配

**Comment by DGYJ-fufu** [comment]
我发现南京工业大学的sid为0，这和其他的学校似乎有点不同，你愿意提供一下pu口袋账号供我测试吗，电子邮箱:dgyj-fufu@foxmail.com
